using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace InterviewProjectTemplate.Data
{
    public enum Roles
    {
        Admin = 1,
    }

    public enum AccountErrorCode
    {
        LOGIN_EMAIL_NOT_CONFIRMED,
        LOGIN_PHONE_NOT_CONFIRMED,
        LOGIN_TWOFACTOR_CODE_REQUIRED,
        LOGIN_TWOFACTOR_CODE_INVALID,
        LOGIN_EMAIL_NOT_REGISTERED,
        LOGIN_INVALID_CREDENTIALS,
        LOGIN_REFRESH_TOKEN_INVALID,
        LOGIN_REFRESH_TOKEN_GENERATION_FAILED,
        LOGIN_USER_NOT_REGISTERED,
        LOGIN_TOKEN_GENERATION_FAILED,
        LOGIN_USER_ALREADY_VERIFIED,
        LOGIN_USER_NOT_FOUND,
        LOGIN_USER_CANNOT_CONFIRM_EMAIL,
        LOGIN_USER_PHONE_NOT_PROVIDED_FOR_EMAIL,
        LOGIN_USER_CANNOT_CONFIRM_PHONE,
        LOGIN_USER_CANNOT_REGISTER,
        LOGIN_USER_CHANGE_PASSWORD_FAILED,
        LOGIN_USER_PASSWORD_RESET_FAILED,
        LOGIN_USER_USERID_MISMATCH,
        LOGIN_USER_INVALID_ROLE,
        LOGIN_USER_VERIFY_EMAIL_FAILED,
        LOGIN_USER_CHANGE_EMAIL_FAILED,
        LOGIN_USER_FORGOT_PASSWORD_FAILED,

        LOGIN_USER_NOT_AUTHENTICATED,
        LOGIN_USER_PROFILE_EXISTS,
        LOGIN_USER_PROFILE_NOTFOUND
    }
}
